spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anyif?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  typeAliasesPackage: sk2a.hello.c
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

  spring.mvc.view.prefix: /templates/
  spring.mvc.view.suffix: .html
