spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anyif?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: sk2a.hello.chann.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    useGeneratedKeys: true
    map-underscore-to-camel-case: true

  spring.mvc.view.prefix: /templates/
  spring.mvc.view.suffix: .html
